image:
  tag: "3.0.0-dev"

podSecurityContext:
  fsGroup: 10001
  fsGroupChangePolicy: OnRootMismatch

persistence:
  size: 20Gi
  s3Sync:
    enabled: true

sharedPvcStorage:
  enabled: true
  mode: dynamic
  name: eva-agent-model-pvc-storage
  size: 20Gi
  accessModes:
    - ReadWriteMany
  storageClass: eva-agent-sc-fs
  reclaimPolicy: Retain

dockerConfig:
  enabled: false
  name: eva-agent-dockerconfig

imagePullSecrets:
  - eva-agent-dockerconfig

awsCredentialsSecretName: aws-credentials

ecrRefresh:
  enabled: true
  schedule: "0 */6 * * *"
  registry: 339713051385.dkr.ecr.ap-northeast-2.amazonaws.com
  region: ap-northeast-2
  secretName: eva-agent-dockerconfig
  kubectlImage: bitnami/kubectl:latest
  serviceAccount:
    create: false
    name: "sa-eva-agent"

serviceAccount:
  create: false
  name: "sa-eva-agent"

service:
  type: ClusterIP
  nodePort:

replicaCount: 1

env:
  # base
  - name: MODEL_CATALOG_FILE
    value: config/model_catalog.json
  - name: LOGURU_LEVEL
    value: INFO

  # vllm
  - name: VLLM_VLM_URL
    value: http://eva-agent-vllm-router-service/v1
  - name: VLLM_LLM_URL
    value: http://eva-agent-vllm-router-service/v1
  - name: VLLM_ENGINE_HEALTH_MODE
    value: k8s

  # qdrant
  - name: QDRANT_BASE_URL
    value: http://eva-agent-qdrant:6333

  # huggingface offline
  - name: HF_HUB_OFFLINE
    value: "1"
  - name: TRANSFORMERS_OFFLINE
    value: "1"

  # o11y
  # - name: LANGFUSE_HOST
  #   value: https://cloud.langfuse.com
  # - name: LANGFUSE_MEDIA_UPLOAD_ENABLED
  #   value: "true"
  # - name: OTEL_EXPORTER_OTLP_ENDPOINT
  #   value: https://cloud.langfuse.com/api/public/otel
  # - name: LANGFUSE_RETENTION_ENABLED
  #   value: "true"
  # - name: LANGFUSE_RETENTION_DAYS
  #   value: "30"
  # - name: LANGFUSE_RETENTION_TIMEZONE
  #   value: UTC
  # - name: LANGFUSE_RETENTION_TRACE_BATCH_SIZE
  #   value: "100"
  # - name: LANGFUSE_MEDIA_RETENTION_ENABLED
  #   value: "true"
  # - name: LANGFUSE_MEDIA_S3_ENDPOINT_URL
  #   value: http://10.157.76.183:9090
  # - name: LANGFUSE_MEDIA_S3_BUCKET
  #   value: langfuse
  # - name: LANGFUSE_MEDIA_S3_PREFIX
  #   value: media/
  # - name: LANGFUSE_MEDIA_S3_FORCE_PATH_STYLE
  #   value: "true"
  # Secret values for S3 access live in values-secret.yaml

  # Azure OpenAI
  # - name: OPENAI_API_TYPE
  #   value: azure
  # - name: OPENAI_API_VERSION
  #   value: 2025-04-01-preview
  # - name: AZURE_OPENAI_ENDPOINT
  #   value: https://dev.dxengws.apim.lgedx.biz/shared-10000
  # - name: DEPLOYMENT_NAME
  #   value: gpt-5-chat-2025-08-07
  # - name: AZURE_MANAGEMENT_BASE_URL
  #   value: https://management.azure.com
  # - name: AZURE_OPENAI_SUBSCRIPTION_ID
  #   value: ""
  # - name: AZURE_OPENAI_RESOURCE_GROUP_NAME
  #   value: ""
  # - name: AZURE_OPENAI_ACCOUNT_NAME
  #   value: ""
  # - name: AZURE_CLIENT_ID
  #   value: ""
  # - name: AZURE_TENANT_ID
  #   value: ""

nodeSelector: {}

vllmEngineHealth:
  rbac:
    create: true
