nameOverride: "eva-agent-ollama"
fullnameOverride: ""

serviceAccount:
  create: false
  name: sa-eva-agent

image:
  pullPolicy: Always

ollama:
  port: 11434
  gpu:
    enabled: true
    type: nvidia
    number: 1

  models:
    # -- List of models to pull at container startup
    pull: []
    # -- List of models to load at container startup
    run:
      - qwen2.5vl:32b  # 2.1.1

persistentVolume:
  enabled: true
  accessModes:
    - ReadWriteMany
  annotations:
    "helm.sh/resource-policy": keep
  # # existingClaim: ""
  # size: 30Gi
  storageClass: "eva-agent-sc-fs"
  # # volumeMode: ""
  subPath: "eva-agent-ollama"
  # # volumeName: ""

extraEnv:
  - name: OLLAMA_KEEP_ALIVE
    value: "-1"
  - name: OLLAMA_MAX_LOADED_MODELS
    value: "2"
  - name: OLLAMA_NUM_PARALLEL
    value: "5"
  - name: OLLAMA_GPU_ONLY
    value: "true"

livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 300
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1
readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 50
  successThreshold: 1
