#TODO: fill secret values up

secretEnv:
  # o11y
  LANGFUSE_SECRET_KEY: "sk-lf-..."
  LANGFUSE_PUBLIC_KEY: "pk-lf-..."
  OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic <redacted>"

  # Azure OpenAI
  OPENAI_API_KEY: xxxxx-xxxxx-xxxxx-xxxxx
  # AZURE_OPENAI_API_KEY: yyyyy-yyyyy-yyyyy-yyyyy
  # AZURE_CLIENT_SECRET:

  # Clova
  # CLOVA_API_KEY: nv-4xxxxxxxxxxx
