#TODO: fill secret values up

secretEnv:
  # o11y
  LANGFUSE_SECRET_KEY: "sk-lf-93b9c389-4d39-476d-963f-2e7b80c3fd8d"
  LANGFUSE_PUBLIC_KEY: "pk-lf-37ecacaf-ae43-4a19-9288-2cbee1f80dce"
  OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Basic cGstbGYtMzdlY2FjYWYtYWU0My00YTE5LTkyODgtMmNiZWUxZjgwZGNlOnNrLWxmLTkzYjljMzg5LTRkMzktNDc2ZC05NjNmLTJlN2I4MGMzZmQ4ZA=="

  # Azure OpenAI
  OPENAI_API_KEY: xxxxx-xxxxx-xxxxx-xxxxx
  # AZURE_OPENAI_API_KEY: yyyyy-yyyyy-yyyyy-yyyyy
  # AZURE_CLIENT_SECRET:

  # Clova
  # CLOVA_API_KEY: nv-4xxxxxxxxxxx
