nameOverride: "eva-agent-qdrant"
fullnameOverride: ""

serviceAccount:
  create: false
  name: sa-eva-agent

image:
  pullPolicy: Always

persistence:
  accessModes: ["ReadWriteOnce"]
  size: 10Gi
  annotations: {}
  storageVolumeName: eva-agent-qdrant-storage
  # storageSubPath: ""
  storageClassName: eva-agent-sc-bs

nodeSelector: {}
