apiVersion: v1
kind: Service
metadata:
  name: eva-agent-qdrant-nodeport
  namespace: eva-agent
spec:
  type: NodePort
  selector:
    app: eva-agent-qdrant
    app.kubernetes.io/instance: eva-agent-qdrant
    app.kubernetes.io/name: eva-agent-qdrant
  ports:
    - name: http
      port: 6333
      targetPort: 6333
      protocol: TCP
      nodePort: 32042
    - name: grpc
      port: 6334
      targetPort: 6334
      protocol: TCP
      nodePort: 32043
